const { SlashCommandBuilder } = require('@discordjs/builders');
const quotes = [
    "Good night, Mo Ran",
    "haru na no ni",
    'Osmanthus wine tastes the same as I remember. But where are those who share the memories?',
    "My name is Yoshikage Kira.",
    "Can't say no homo in your second life.",
    "Witness the power of Guhua!",
    "You will join the grave of the Deep Fried Empress Song.",
    "There was Fuxi in heaven, Yanluo in hell, and in the mortal realm, there was Mo Ran.",
    "May my final stand be a monument to chivalry.",
    "an apple a day keeps deez nuts at bay ~ Josie",
    "May knowledge guide you.",
    "Shizun...Please, I can't take it anymore...",
    "Two lifetimes - they belong to you. No regrets.",
    "The endless steps stained with blood, that was the path he took to take you home.",
    "In my previous life, in this life, I've always loved you. In the future, I'm also willing.",
    "Drink the wine he drank, endure the pain he endured.",
    "Everyday means everyday :dickslap:",
    "Ge... we don't have a shizun anymore.",
    "We are the heirs to the throne of love! Battle Lovers!",
    "Go somewhere that will welcome you... this time no matter where you want to go, this master will accompany you.",
    "Only after having met you did I rediscover that it's such a simple thing to be happy",
    "Your Highness I understand your everything. Your courage, your dispair; your kindness, your pain; your resentment, your hate; your intelligence, your foolishness",
    "GAINS OVER SHAME. MONEY OVER LIFE. HA HA HA.",
    "Body in abyss, heart in paradise.",
    "If I can't be a prince, I will be a horse",
    "What does freedom really mean, when demanded of you by a god?",
    "I just think we're missing out if we're not trying different things and having fun. Life's too short.",
    "It's no one's business to decide who's weak or strong.",
    "Ho ho.",
    "Ho ho.",
    "Ho ho.",
    "Once the snow is thick enough, we can eat it",
    "Everything that's happened in the past, I'll repay it all to you today.",
    "I am... not interested, little sun. Try again when you have become a man.",
    "Give up on your dreams and die.",
    "Those who can't abandon anything, can't change anything.",
    "After all, miracles happen everyday, do they not?",
    "To know sorrow is not terrifying. What is terrifying is to know you can't go back to happiness you could have.",
    "Fear is not evil. It tells you what weakness is. And once you know your weakness, you can become stronger as well as kinder.",
    "Come on, let's get moving. We're not frozen in place, after all.",
    "Once you've all witnessed the wrath of the spiked butt...",
    "Hell is too cold, I came to die with you.",
    "Another day in the life of Eorzea's errand boy",
    "i am one hell of a butler",
    "We have two lives, and the second begins when we realize we only have one.",
    "Hell is empty and all the devils are here ~ Shakespeare",
    "Ahes to ashes, dust to dust, oil them bones, before they rust.",
    "To die in battle for you is my greatest honour",
    "If your dream is to save the common people, then my dream is only you",
    "There is no banquet in this world that doesn't come to an end.",
    "I pray to never rest in peace.",
    "Remember: when humans ascend, they are still human; when they fall, they are still human",
    "I don't know if you all missed me, but I haven't thought about any of you at all.",
    "Standing there in the rain, under the haitang blossoms dancing atop the barrier, he looked at Mo Ran for the first time, thoroughly and carefully, looked at this man who was promising him a lifetime.",
    "I might not be able to decide whether the road is easy or not, but whether I walk it is entirely up to me",
    "But what he hadn't expected was that when everyone feared him and flattered him, Lan WangJi scolded him right in his face; when everyone spurned him and loathed him, Lan WangJi stood by his side",
    "Who cares about the crowded, broad road? I'll walk the single-plank bridge into the night…",
    "Suddenly, he felt that the world had no place for him, despite how large it was.",
    "I used to think of you as my soulmate. / I still am.",
    "Hatred could blind a person's eyes, making him unable to admit anything in favor of his enemy.",
    "How is it that you are real? My dreams never created something like you. I still have to pinch myself, because I'm amazed you are true.",
    "For a promise, I once gave up my sword for a flute.",
    "Xiao XingChen, the bright moon, the gentle breeze; Song ZiChen, the distant snow, the bitter frost",
    "Who cares about the crowded broad street, I'll walk on my single plank bridge till it's dark.",
    "Rebellion against orthodoxy? What kind of orthodoxy is that? Lan Zhan, do you still remember the promise we have made together? Throughout this life, I wished I could eliminate all traitors, and support the weak against the strong. But tell me now, who's stronger and weaker, who's right and who's wrong. Is this the promise that we pledged our lives to keep?",
    "Even though the world was large, how many people could say, you need not to become strong; I am here, of course I will not let others harm you?",
    "Stupid author stupid novel!",
    "You probably won't be truly happy until you're a geezer - Iwaizumi",
    "You really are a piece of crap - Iwaizumi",
    "Could you stop calling me a crappy guy'? - Oikawa",
    "'Straightforward and pure' coming from you is already impure - Iwaizumi",
    "Iwa-chan, are you my mom? - Oikawa",
    "What are you thinking? You won't get your way! - Hinata",
    "Japan! - Hinata",
    "Hey! There's nowhere to run! - Daichi",
];

module.exports = {
    data: new SlashCommandBuilder()
        .setName('quote')
        .setDescription('Brainrot at its finest!'),
    async execute(interaction) {
        await interaction.reply(quotes[Math.floor(Math.random() * quotes.length)]);
    },
};